version : '3.3'

services:
    app:
        build:
            context: ./server
            args:
                BUILD_ENV: "${BUILD_ENV:-production}"
                OVERCOOKED_BRANCH: "${OVERCOOKED_BRANCH:-main}"
                AGENT_BRANCH: "${AGENT_BRANCH:-main}"
                GRAPHICS: "${GRAPHICS:-overcooked_graphics_v2.2.js}"
        environment: 
            FLASK_ENV: "${BUILD_ENV:-production}"
        ports:
            - "5000:5000"

